// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// randomShuffle
Rcpp::NumericVector randomShuffle(Rcpp::NumericVector a);
RcppExport SEXP ModelMatch_randomShuffle(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a(aSEXP);
    __result = Rcpp::wrap(randomShuffle(a));
    return __result;
END_RCPP
}
// permute_within_groups_cpp
List permute_within_groups_cpp(List strata);
RcppExport SEXP ModelMatch_permute_within_groups_cpp(SEXP strataSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type strata(strataSEXP);
    __result = Rcpp::wrap(permute_within_groups_cpp(strata));
    return __result;
END_RCPP
}
// meanC
double meanC(NumericVector x);
RcppExport SEXP ModelMatch_meanC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(meanC(x));
    return __result;
END_RCPP
}
// within_group_mean_cpp
NumericVector within_group_mean_cpp(List strata, NumericVector prediction, NumericVector response, float shift);
RcppExport SEXP ModelMatch_within_group_mean_cpp(SEXP strataSEXP, SEXP predictionSEXP, SEXP responseSEXP, SEXP shiftSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type strata(strataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prediction(predictionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type response(responseSEXP);
    Rcpp::traits::input_parameter< float >::type shift(shiftSEXP);
    __result = Rcpp::wrap(within_group_mean_cpp(strata, prediction, response, shift));
    return __result;
END_RCPP
}
