# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

randomShuffle <- function(a) {
    .Call('ModelMatch_randomShuffle', PACKAGE = 'ModelMatch', a)
}

permute_within_groups_cpp <- function(strata) {
    .Call('ModelMatch_permute_within_groups_cpp', PACKAGE = 'ModelMatch', strata)
}

meanC <- function(x) {
    .Call('ModelMatch_meanC', PACKAGE = 'ModelMatch', x)
}

within_group_mean_cpp <- function(strata, prediction, response, shift = 0) {
    .Call('ModelMatch_within_group_mean_cpp', PACKAGE = 'ModelMatch', strata, prediction, response, shift)
}

